import type { Job, Offer, Provider, ServiceCategory } from "./types";

export const serviceCategories: {
  name: ServiceCategory;
  description: string;
  emergencyReady: boolean;
}[] = [
  { name: "Electrical", description: "Outlets, breakers, sparks", emergencyReady: true },
  { name: "Plumbing", description: "Leaks, sinks, drains, toilets", emergencyReady: true },
  { name: "HVAC", description: "Heating, cooling, filters, repairs", emergencyReady: true },
  { name: "Cleaning", description: "Deep clean, move-out, urgent cleanup", emergencyReady: false },
  { name: "Moving", description: "Furniture, boxes, same-day help", emergencyReady: false },
  { name: "Handyman", description: "Repairs, installs, small projects", emergencyReady: false },
  { name: "Appliance Repair", description: "Washers, dryers, ovens, fridges", emergencyReady: false },
  { name: "Mobile Mechanic", description: "Car diagnostics and local repairs", emergencyReady: false },
  { name: "Painting", description: "Interior, exterior, touch-ups", emergencyReady: false },
  { name: "Carpentry", description: "Trim, doors, shelves, wood repair", emergencyReady: false },
  { name: "Landscaping", description: "Yard cleanup, mowing, planting", emergencyReady: false },
  { name: "Home Repair", description: "General home repairs and fixes", emergencyReady: true },
  { name: "Delivery", description: "Local errands, pickup, delivery", emergencyReady: false },
  { name: "Tax Help", description: "Tax prep and paperwork support", emergencyReady: false },
  { name: "Immigration Paperwork Help", description: "Forms, translation, document prep", emergencyReady: false },
  { name: "Translation", description: "Document and appointment translation", emergencyReady: false },
  { name: "Student Help", description: "Tutoring, moving, errands, setup", emergencyReady: false },
  { name: "Web Design", description: "Simple websites and local business pages", emergencyReady: false },
  { name: "General Local Services", description: "Any local help not listed above", emergencyReady: false },
];

export const providers: Provider[] = [
  {
    id: "ahmed-plumbing",
    name: "Ahmed Plumbing",
    category: "Plumbing",
    categories: ["Plumbing", "Home Repair"],
    rating: 4.9,
    kycStatus: "Verified",
    completedJobs: 42,
    etaMinutes: 20,
    trustScore: 94,
    reliabilityScore: 91,
    responseTimeMinutes: 12,
    priceRange: "$80 - $180",
    startingPrice: "$80",
    hourlyRate: "$95/hr",
    profilePhoto: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=300&q=80",
    coverPhoto: "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=1400&q=80",
    bio:
      "Emergency-focused plumbing provider specializing in leak repair, drain issues, sink installs, and urgent water shutoff support for apartments and homes.",
    skills: ["Leak repair", "Drain cleaning", "Sink installation", "Toilet repair", "Emergency shutoff"],
    yearsExperience: 5,
    serviceArea: "Downtown, Midtown, West Loop",
    availability: "Available now",
    languages: ["English", "Spanish", "Arabic"],
    portfolioPhotos: [
      "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=700&q=80",
      "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=700&q=80",
      "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=700&q=80",
    ],
    beforeAfterPhotos: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=700&q=80",
      "https://images.unsplash.com/photo-1600607687644-c7171b42498f?auto=format&fit=crop&w=700&q=80",
    ],
    licenses: ["City plumbing contractor license"],
    certifications: ["Water damage prevention basics", "Drain repair certification"],
    insuranceStatus: "Insurance uploaded",
    badges: ["Verified Provider", "Top Rated", "Fast Response", "Emergency Provider", "Insured", "ID Verified", "Phone Verified"],
    verificationLevel: 5,
    servicePackages: [
      { name: "Small leak repair", description: "Quick repair for under-sink or visible pipe leaks.", price: "Starting from $80" },
      { name: "Sink installation", description: "Install or replace kitchen and bathroom sinks.", price: "Starting from $150" },
      { name: "Emergency plumbing visit", description: "Urgent leak triage and immediate containment.", price: "Starting from $120" },
      { name: "Drain cleaning", description: "Clear slow or blocked drains with standard tools.", price: "Starting from $100" },
    ],
    reviews: [
      { customer: "Nadia R.", rating: 5, text: "Arrived fast, stopped the leak, and explained every step.", date: "Apr 2026" },
      { customer: "James L.", rating: 5, text: "Clean work and fair pricing for a late evening emergency.", date: "Mar 2026" },
      { customer: "Priya S.", rating: 4.8, text: "Great communication and the repair held up perfectly.", date: "Feb 2026" },
    ],
    workHistory: [
      { title: "Kitchen sink leaking", category: "Plumbing", status: "Completed", rating: 5 },
      { title: "Emergency drain backup", category: "Plumbing", status: "Completed", rating: 4.9 },
      { title: "Bathroom faucet replacement", category: "Plumbing", status: "Completed", rating: 4.8 },
    ],
    disputeCount: 0,
    noShowReports: 0,
  },
  {
    id: "mike-electric",
    name: "Mike Electric",
    category: "Electrical",
    categories: ["Electrical", "HVAC"],
    rating: 4.8,
    kycStatus: "Verified",
    completedJobs: 35,
    etaMinutes: 25,
    trustScore: 91,
    reliabilityScore: 88,
    responseTimeMinutes: 15,
    priceRange: "$95 - $240",
    startingPrice: "$95",
    hourlyRate: "$110/hr",
    profilePhoto: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=300&q=80",
    coverPhoto: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=1400&q=80",
    bio:
      "Licensed residential electrician for outlet repairs, breaker issues, emergency spark calls, fixture upgrades, and safety-first troubleshooting.",
    skills: ["Outlet repair", "Breaker checks", "Fixture install", "Panel triage", "Safety inspections"],
    yearsExperience: 7,
    serviceArea: "Northside, Lakeshore, River District",
    availability: "Available in 25 minutes",
    languages: ["English", "Spanish"],
    portfolioPhotos: [
      "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=700&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=700&q=80",
      "https://images.unsplash.com/photo-1621905252472-e477c4c7b9a0?auto=format&fit=crop&w=700&q=80",
    ],
    beforeAfterPhotos: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=700&q=80",
      "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=700&q=80",
    ],
    licenses: ["Residential electrician license"],
    certifications: ["Electrical safety certification"],
    insuranceStatus: "Insurance uploaded",
    badges: ["Verified Provider", "Emergency Provider", "Insured", "Background Checked", "Phone Verified"],
    verificationLevel: 5,
    servicePackages: [
      { name: "Outlet repair", description: "Diagnose and repair sparking or non-working outlets.", price: "Starting from $95" },
      { name: "Breaker inspection", description: "Check breaker trips, overloads, and panel concerns.", price: "Starting from $120" },
      { name: "Light fixture install", description: "Replace or install fixtures safely.", price: "Starting from $140" },
    ],
    reviews: [
      { customer: "Erin T.", rating: 5, text: "Handled a scary outlet issue professionally.", date: "Apr 2026" },
      { customer: "Mo H.", rating: 4.7, text: "Clear safety advice and quick repair.", date: "Mar 2026" },
    ],
    workHistory: [
      { title: "Outlet sparks when used", category: "Electrical", status: "On the way", rating: 5 },
      { title: "Bedroom light fixture install", category: "Electrical", status: "Completed", rating: 4.8 },
    ],
    disputeCount: 1,
    noShowReports: 0,
  },
  {
    id: "sara-cleaning",
    name: "Sara Cleaning",
    category: "Cleaning",
    categories: ["Cleaning"],
    rating: 4.7,
    kycStatus: "Verified",
    completedJobs: 58,
    etaMinutes: 40,
    trustScore: 93,
    reliabilityScore: 92,
    responseTimeMinutes: 18,
    priceRange: "$90 - $260",
    startingPrice: "$90",
    hourlyRate: "$45/hr",
    profilePhoto: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80",
    coverPhoto: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1400&q=80",
    bio:
      "Reliable cleaning team for apartment deep cleans, move-out cleaning, office refreshes, and urgent cleanup requests.",
    skills: ["Deep cleaning", "Move-out cleaning", "Kitchen detail", "Office cleaning", "Urgent cleanup"],
    yearsExperience: 6,
    serviceArea: "Citywide within 8 miles",
    availability: "Available today",
    languages: ["English", "Spanish"],
    portfolioPhotos: [
      "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=700&q=80",
      "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=700&q=80",
      "https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=700&q=80",
    ],
    beforeAfterPhotos: [
      "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=700&q=80",
      "https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=700&q=80",
    ],
    licenses: ["Business registration"],
    certifications: ["Eco-safe cleaning methods"],
    insuranceStatus: "Insurance uploaded",
    badges: ["Verified Provider", "Top Rated", "Insured", "Fast Response", "Phone Verified"],
    verificationLevel: 4,
    servicePackages: [
      { name: "Apartment deep clean", description: "Bathrooms, kitchen, floors, dusting, and high-touch areas.", price: "Starting from $140" },
      { name: "Move-out cleaning", description: "Detailed clean for rental handoff or listing photos.", price: "Starting from $220" },
      { name: "Urgent cleanup", description: "Same-day mess and spill cleanup support.", price: "Starting from $110" },
    ],
    reviews: [
      { customer: "Olivia M.", rating: 4.8, text: "Very thorough and easy to schedule.", date: "Apr 2026" },
      { customer: "Devon P.", rating: 4.7, text: "Great move-out cleaning with clear pricing.", date: "Feb 2026" },
    ],
    workHistory: [
      { title: "Need apartment deep cleaning", category: "Cleaning", status: "Request posted", rating: 4.7 },
      { title: "Office cleanup", category: "Cleaning", status: "Completed", rating: 4.9 },
    ],
    disputeCount: 0,
    noShowReports: 1,
  },
  {
    id: "omar-handyman",
    name: "Omar Handyman",
    category: "Handyman",
    categories: ["Handyman", "Moving"],
    rating: 4.6,
    kycStatus: "Pending",
    completedJobs: 12,
    etaMinutes: 30,
    trustScore: 78,
    reliabilityScore: 74,
    responseTimeMinutes: 28,
    priceRange: "$60 - $160",
    startingPrice: "$60",
    hourlyRate: "$70/hr",
    profilePhoto: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
    coverPhoto: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1400&q=80",
    bio:
      "Handyman and small moving helper for furniture assembly, wall mounting, minor repairs, and quick household tasks.",
    skills: ["Furniture assembly", "Wall mounting", "Minor repairs", "Moving help", "Fixture replacement"],
    yearsExperience: 3,
    serviceArea: "Downtown and nearby suburbs",
    availability: "Available this afternoon",
    languages: ["English", "Spanish", "Arabic"],
    portfolioPhotos: [
      "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=700&q=80",
      "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=700&q=80",
      "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=700&q=80",
    ],
    beforeAfterPhotos: [
      "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=700&q=80",
      "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=700&q=80",
    ],
    licenses: ["KYC pending"],
    certifications: ["Tool safety orientation"],
    insuranceStatus: "Insurance not uploaded",
    badges: ["New Provider", "Tools Verified", "Background Check Pending"],
    verificationLevel: 2,
    servicePackages: [
      { name: "Furniture assembly", description: "Assemble desks, beds, shelves, and small furniture.", price: "Starting from $70" },
      { name: "Wall mount visit", description: "Mount shelves, mirrors, and simple TV brackets.", price: "Starting from $90" },
      { name: "Small moving help", description: "Move furniture inside a home or into a truck.", price: "Starting from $120" },
    ],
    reviews: [
      { customer: "Chris W.", rating: 4.6, text: "Helpful and affordable for furniture assembly.", date: "Apr 2026" },
    ],
    workHistory: [
      { title: "Need help moving furniture", category: "Moving", status: "Completed", rating: 4.6 },
      { title: "Bookshelf assembly", category: "Handyman", status: "Completed", rating: 4.5 },
    ],
    disputeCount: 1,
    noShowReports: 2,
  },
];

export const jobs: Job[] = [
  {
    id: "job-001",
    title: "Kitchen sink leaking",
    category: "Plumbing",
    urgency: "High",
    status: "Offers received",
    locationArea: "West Loop",
    description: "My sink is leaking and water is everywhere under the cabinet.",
    aiSummary:
      "Customer reports heavy water leaking under the kitchen sink. Possible cause is a loose drain pipe or broken supply line. Urgency is high.",
    possibleCause: "Loose drain pipe, failed supply line, or broken sink drain seal",
    priceRange: "$90 - $220",
    safetyNotes: ["Turn off the water valve if possible", "Move electronics away from water", "Take before photos"],
    toolsNeeded: ["Plumbing tools", "Replacement fittings", "Sealant", "Towels"],
    createdAt: "Today, 8:42 AM",
  },
  {
    id: "job-002",
    title: "Outlet sparks when used",
    category: "Electrical",
    urgency: "Emergency",
    status: "Provider on the way",
    locationArea: "River District",
    description: "The living room outlet sparks when I plug anything in.",
    aiSummary:
      "Customer reports sparks from an outlet during use. Urgency is emergency due to fire risk. Provider should inspect wiring, outlet, and breaker load.",
    possibleCause: "Loose wiring, damaged outlet, overloaded circuit, or faulty plug contact",
    priceRange: "$120 - $320",
    safetyNotes: ["Stop using the outlet", "Turn off the breaker if safe", "Keep children away"],
    toolsNeeded: ["Voltage tester", "Replacement outlet", "Wire connectors", "Insulated tools"],
    createdAt: "Today, 9:10 AM",
  },
  {
    id: "job-003",
    title: "Need apartment deep cleaning",
    category: "Cleaning",
    urgency: "Medium",
    status: "Request posted",
    locationArea: "Midtown",
    description: "Two-bedroom apartment needs deep cleaning before guests arrive.",
    aiSummary:
      "Customer needs a two-bedroom deep clean before guests arrive. Medium urgency because timing matters but no safety risk is reported.",
    possibleCause: "Routine deep cleaning request with time sensitivity",
    priceRange: "$130 - $260",
    safetyNotes: ["Confirm access details", "Secure valuables", "List priority rooms"],
    toolsNeeded: ["Cleaning supplies", "Vacuum", "Mop", "Bathroom and kitchen cleaners"],
    createdAt: "Yesterday, 5:20 PM",
  },
  {
    id: "job-004",
    title: "Need help moving furniture",
    category: "Moving",
    urgency: "Low",
    status: "Completed",
    locationArea: "Downtown",
    description: "Need two people to move couch and dresser into a small truck.",
    aiSummary:
      "Customer requested furniture moving help for a couch and dresser. Low urgency and completed with no dispute.",
    possibleCause: "General moving labor request",
    priceRange: "$80 - $180",
    safetyNotes: ["Clear walking paths", "Use lifting straps", "Protect walls and floors"],
    toolsNeeded: ["Moving straps", "Dolly", "Furniture pads"],
    createdAt: "Apr 27, 2026",
  },
];

export const offers: Offer[] = [
  {
    id: "offer-001",
    jobId: "job-001",
    providerId: "ahmed-plumbing",
    price: 160,
    etaMinutes: 20,
    message: "I can arrive in 20 minutes and stop the leak before checking the damaged fitting.",
    fairPriceStatus: "Fair",
    aiMatchReason:
      "Ahmed Plumbing is the best match because he is verified, has a 4.9 rating, completed 42 similar jobs, and can arrive in 20 minutes.",
  },
  {
    id: "offer-002",
    jobId: "job-001",
    providerId: "omar-handyman",
    price: 95,
    etaMinutes: 30,
    message: "I can inspect the leak and attempt a small repair if no licensed plumbing work is required.",
    fairPriceStatus: "Unusually low",
    aiMatchReason:
      "Omar is nearby and affordable, but his KYC is still pending and this job may require a verified emergency plumber.",
  },
  {
    id: "offer-003",
    jobId: "job-001",
    providerId: "mike-electric",
    price: 280,
    etaMinutes: 25,
    message: "I can check water near electrical outlets and refer plumbing repair if needed.",
    fairPriceStatus: "Too high",
    aiMatchReason:
      "Mike is verified and strong for electrical safety, but his primary category does not match the plumbing repair need.",
  },
];

export const demoUsers = [
  { name: "Ava Customer", role: "Customer", status: "Active", jobs: 3 },
  { name: "Ahmed Plumbing", role: "Provider", status: "Verified", jobs: 42 },
  { name: "Mike Electric", role: "Provider", status: "Verified", jobs: 35 },
  { name: "Omar Handyman", role: "Provider", status: "KYC pending", jobs: 12 },
];

export const disputes = [
  { id: "DSP-1001", job: "Outlet sparks when used", status: "Under review", severity: "High", provider: "Mike Electric" },
  { id: "DSP-1002", job: "Wall mounting", status: "Resolved", severity: "Low", provider: "Omar Handyman" },
  { id: "NS-2040", job: "Apartment cleanup", status: "Submitted", severity: "Medium", provider: "Sara Cleaning" },
];

export const platformStats = {
  totalCustomers: 1280,
  totalProviders: 214,
  totalJobs: 3920,
  completedJobs: 3412,
  emergencyJobs: 438,
  disputes: 21,
};

export const jobTimeline = [
  "Request posted",
  "Request reviewed",
  "Offers received",
  "Provider accepted",
  "Provider on the way",
  "Job started",
  "Job completed",
  "Review submitted",
];

export const providerPlans = [
  {
    name: "Free launch",
    price: "$0",
    note: "The first version is free for customers and providers while the marketplace grows.",
    features: ["Unlimited request posting", "Unlimited browsing", "Basic provider profiles", "No commission"],
  },
  {
    name: "Future growth",
    price: "Later",
    note: "Monetization can wait until the marketplace has real local supply and demand.",
    features: ["Featured providers", "Urgent request fee", "Verified provider badge", "Pro provider plan"],
  },
  {
    name: "Future scale",
    price: "After traction",
    note: "Commission can be considered only after the platform proves repeat usage.",
    features: ["Optional commission", "Business accounts", "Category sponsorships", "Advanced matching tools"],
  },
];
